version: '3'
services:
  app:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - NUXT_PARSER_URL=http://parser:8080
      - NUXT_DB_URL=postgres://postgres:postgres@db:5432/tools
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tools
  parser:
    build:
      context: ./parser
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./parser:/app
  indexer:
    build:
      context: ./indexer
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/tools?sslmode=disable
    restart: on-failure
